# Generated by Django 5.1.1 on 2024-09-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nifuate', '0002_onlinemember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='causes')),
                ('description', models.TextField(max_length=500)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('collected_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OnlineMember',
        ),
    ]
